// This file was generated by SquareLine Studio
// SquareLine Studio version: SquareLine Studio 1.5.4
// LVGL version: 9.2.2
// Project name: Makita_Chrager

#ifndef _MAKITA_CHRAGER_UI_H
#define _MAKITA_CHRAGER_UI_H

#ifdef __cplusplus
extern "C" {
#endif

#include "lvgl/lvgl.h"

#include "ui_helpers.h"
#include "ui_events.h"
#include "ui_theme_manager.h"
#include "ui_themes.h"


///////////////////// SCREENS ////////////////////

#include "screens/ui_Screen3.h"

///////////////////// VARIABLES ////////////////////

extern lv_anim_t * FadeIn_Animation(lv_obj_t * TargetObject, int delay);
extern lv_anim_t * FadeOut_Animation(lv_obj_t * TargetObject, int delay);
extern lv_anim_t * Opacity_Animation(lv_obj_t * TargetObject, int delay);

// EVENTS

extern lv_obj_t * ui____initial_actions0;

// UI INIT
void ui_init(void);
void ui_destroy(void);

#ifdef __cplusplus
} /*extern "C"*/
#endif

#endif
