// This file was generated by SquareLine Studio
// SquareLine Studio version: SquareLine Studio 1.5.4
// LVGL version: 9.2.2
// Project name: Makita_Chrager

#ifndef _UI_THEMES_H
#define _UI_THEMES_H

#ifdef __cplusplus
extern "C" {
#endif

#define UI_THEME_COLOR_LIGHTBLUE 0
#define UI_THEME_COLOR_FULLCHARGE 1
#define UI_THEME_COLOR_BTNFOCUSED 2
#define UI_THEME_COLOR_DARKBLUE 3

#define UI_THEME_DEFAULT 0

#define UI_THEME_FULLCHARGE 1

#define UI_THEME_BTNGRADIENT 2

extern const ui_theme_variable_t _ui_theme_color_LightBlue[3];
extern const ui_theme_variable_t _ui_theme_alpha_LightBlue[3];

extern const ui_theme_variable_t _ui_theme_color_FullCharge[3];
extern const ui_theme_variable_t _ui_theme_alpha_FullCharge[3];

extern const ui_theme_variable_t _ui_theme_color_btnFocused[3];
extern const ui_theme_variable_t _ui_theme_alpha_btnFocused[3];

extern const ui_theme_variable_t _ui_theme_color_DarkBlue[3];
extern const ui_theme_variable_t _ui_theme_alpha_DarkBlue[3];

extern const uint32_t * ui_theme_colors[3];
extern const uint8_t * ui_theme_alphas[3];
extern uint8_t ui_theme_idx;

void ui_theme_set(uint8_t theme_idx);

#ifdef __cplusplus
} /*extern "C"*/
#endif

#endif
