// This file was generated by SquareLine Studio
// SquareLine Studio version: SquareLine Studio 1.5.4
// LVGL version: 9.2.2
// Project name: Makita_Chrager

#include "ui.h"


const ui_theme_variable_t _ui_theme_color_LightBlue[3] = {0x39A7FF, 0x39A7FF, 0x2196F3};
const ui_theme_variable_t _ui_theme_alpha_LightBlue[3] = {255, 255, 255};

const ui_theme_variable_t _ui_theme_color_FullCharge[3] = {0x09EE4A, 0x09EE4A, 0x09EE4A};
const ui_theme_variable_t _ui_theme_alpha_FullCharge[3] = {255, 255, 255};

const ui_theme_variable_t _ui_theme_color_btnFocused[3] = {0x00D127, 0x00D127, 0x00D127};
const ui_theme_variable_t _ui_theme_alpha_btnFocused[3] = {255, 255, 255};

const ui_theme_variable_t _ui_theme_color_DarkBlue[3] = {0x02009C, 0x02009C, 0x0D0AF9};
const ui_theme_variable_t _ui_theme_alpha_DarkBlue[3] = {255, 255, 255};
uint8_t ui_theme_idx = UI_THEME_DEFAULT;


void ui_theme_set(uint8_t theme_idx)
{
    ui_theme_idx = theme_idx;
    _ui_theme_set_variable_styles(UI_VARIABLE_STYLES_MODE_FOLLOW);
}

