// This file was generated by SquareLine Studio
// SquareLine Studio version: SquareLine Studio 1.5.4
// LVGL version: 9.2.2
// Project name: Makita_Chrager

#ifndef UI_SCREEN3_H
#define UI_SCREEN3_H

#ifdef __cplusplus
extern "C" {
#endif

// SCREEN: ui_Screen3
extern void ui_Screen3_screen_init(void);
extern void ui_Screen3_screen_destroy(void);
extern lv_obj_t * ui_Screen3;
extern lv_obj_t * ui_TabView1;
extern lv_obj_t * ui_Home;
extern lv_obj_t * ui_NumericPanel;
extern lv_obj_t * ui_NumericBatt1;
extern lv_obj_t * ui_VoltLabel1;
extern lv_obj_t * ui_Label61;
extern lv_obj_t * ui_NumericBatt2;
extern lv_obj_t * ui_VoltLabel2;
extern lv_obj_t * ui_Label59;
extern lv_obj_t * ui_NumericBatt3;
extern lv_obj_t * ui_VoltLabel3;
extern lv_obj_t * ui_Label63;
extern lv_obj_t * ui_NumericBatt4;
extern lv_obj_t * ui_VoltLabel4;
extern lv_obj_t * ui_Label65;
extern lv_obj_t * ui_NumericBatt5;
extern lv_obj_t * ui_VoltLabel5;
extern lv_obj_t * ui_Label67;
extern lv_obj_t * ui_NumericBatt6;
extern lv_obj_t * ui_VoltLabel6;
extern lv_obj_t * ui_Label69;
extern lv_obj_t * ui_NumericBatt7;
extern lv_obj_t * ui_VoltLabel7;
extern lv_obj_t * ui_Label71;
extern lv_obj_t * ui_NumericBatt8;
extern lv_obj_t * ui_VoltLabel8;
extern lv_obj_t * ui_Label73;
extern lv_obj_t * ui_VoltBatt1;
extern lv_obj_t * ui_VoltLabel9;
extern lv_obj_t * ui_Label10;
extern lv_obj_t * ui_VoltBatt2;
extern lv_obj_t * ui_VoltLabel10;
extern lv_obj_t * ui_Label11;
extern lv_obj_t * ui_VoltBatt3;
extern lv_obj_t * ui_VoltLabel11;
extern lv_obj_t * ui_Label15;
extern lv_obj_t * ui_VoltBatt4;
extern lv_obj_t * ui_VoltLabel12;
extern lv_obj_t * ui_Label16;
extern lv_obj_t * ui_VoltBatt5;
extern lv_obj_t * ui_VoltLabel13;
extern lv_obj_t * ui_Label17;
extern lv_obj_t * ui_VoltBatt6;
extern lv_obj_t * ui_VoltLabel14;
extern lv_obj_t * ui_Label18;
extern lv_obj_t * ui_VoltBatt7;
extern lv_obj_t * ui_VoltLabel15;
extern lv_obj_t * ui_Label20;
extern lv_obj_t * ui_VoltBatt8;
extern lv_obj_t * ui_VoltLabel16;
extern lv_obj_t * ui_Label22;
extern lv_obj_t * ui_BarPanel;
extern lv_obj_t * ui_VoltBar1;
extern lv_obj_t * ui_VoltBar2;
extern lv_obj_t * ui_VoltBar3;
extern lv_obj_t * ui_VoltBar4;
extern lv_obj_t * ui_VoltBar5;
extern lv_obj_t * ui_VoltBar6;
extern lv_obj_t * ui_VoltBar7;
extern lv_obj_t * ui_VoltBar8;
extern lv_obj_t * ui_Infos;
extern void ui_event_btnInfoBatt1(lv_event_t * e);
extern lv_obj_t * ui_btnInfoBatt1;
extern lv_obj_t * ui_Label2;
extern void ui_event_btnInfoBatt2(lv_event_t * e);
extern lv_obj_t * ui_btnInfoBatt2;
extern lv_obj_t * ui_Label6;
extern void ui_event_btnInfoBatt3(lv_event_t * e);
extern lv_obj_t * ui_btnInfoBatt3;
extern lv_obj_t * ui_Label7;
extern void ui_event_btnInfoBatt4(lv_event_t * e);
extern lv_obj_t * ui_btnInfoBatt4;
extern lv_obj_t * ui_Label8;
extern void ui_event_btnInfoBatt5(lv_event_t * e);
extern lv_obj_t * ui_btnInfoBatt5;
extern lv_obj_t * ui_Label12;
extern void ui_event_btnInfoBatt6(lv_event_t * e);
extern lv_obj_t * ui_btnInfoBatt6;
extern lv_obj_t * ui_Label1;
extern void ui_event_btnInfoBatt7(lv_event_t * e);
extern lv_obj_t * ui_btnInfoBatt7;
extern lv_obj_t * ui_Label14;
extern void ui_event_btnInfoBatt8(lv_event_t * e);
extern lv_obj_t * ui_btnInfoBatt8;
extern lv_obj_t * ui_Label19;
extern lv_obj_t * ui_Panel2;
extern lv_obj_t * ui_Label23;
extern lv_obj_t * ui_Label27;
extern lv_obj_t * ui_Label28;
extern lv_obj_t * ui_Label29;
extern lv_obj_t * ui_Label21;
extern lv_obj_t * ui_Label32;
extern lv_obj_t * ui_Label34;
extern lv_obj_t * ui_lbTotalChargingTime;
extern lv_obj_t * ui_lbWh;
extern lv_obj_t * ui_lbAh;
extern lv_obj_t * ui_lbMinTemp;
extern lv_obj_t * ui_lbMaxTemp;
extern lv_obj_t * ui_lbSoH;
extern lv_obj_t * ui_lbSoC;
extern void ui_event_btnClose(lv_event_t * e);
extern lv_obj_t * ui_btnClose;
extern lv_obj_t * ui_Label13;
extern void ui_event_btnStromkurve(lv_event_t * e);
extern lv_obj_t * ui_btnStromkurve;
extern lv_obj_t * ui_Label30;
extern void ui_event_btnSpannungskurve(lv_event_t * e);
extern lv_obj_t * ui_btnSpannungskurve;
extern lv_obj_t * ui_Label31;
extern lv_obj_t * ui_Stromkurve;
extern lv_obj_t * ui_LabelChartStromkurve;
extern void ui_event_ChartStromkurve(lv_event_t * e);
extern lv_obj_t * ui_ChartStromkurve;
extern lv_obj_t * ui_ChartStromkurve_Xaxis;
extern lv_obj_t * ui_ChartStromkurve_Yaxis1;
extern lv_obj_t * ui_ChartStromkurve_Yaxis2;
extern lv_obj_t * ui_Spannungskurve;
extern lv_obj_t * ui_LabelChartSpannungskurve;
extern void ui_event_ChartSpannungskurve(lv_event_t * e);
extern lv_obj_t * ui_ChartSpannungskurve;
extern lv_obj_t * ui_ChartSpannungskurve_Xaxis;
extern lv_obj_t * ui_ChartSpannungskurve_Yaxis1;
extern lv_obj_t * ui_ChartSpannungskurve_Yaxis2;
extern lv_obj_t * ui_Settings;
extern void ui_event_btnSetCharchingSpeed(lv_event_t * e);
extern lv_obj_t * ui_btnSetCharchingSpeed;
extern void ui_event_LabelCharchingSpeed(lv_event_t * e);
extern lv_obj_t * ui_LabelCharchingSpeed;
extern lv_obj_t * ui_LabelOTA;
extern void ui_event_HelpOTA(lv_event_t * e);
extern lv_obj_t * ui_HelpOTA;
extern lv_obj_t * ui_Label77;
extern lv_obj_t * ui_ddOTA;
extern lv_obj_t * ui_lbWLAN;
extern lv_obj_t * ui_SwitchWLANOnOff;
extern lv_obj_t * ui_lbShowVoltage;
extern void ui_event_SwitchShowVoltage(lv_event_t * e);
extern lv_obj_t * ui_SwitchShowVoltage;
extern lv_obj_t * ui_btnReboot;
extern lv_obj_t * ui_Label4;
extern lv_obj_t * ui_btnCheckUpdates;
extern lv_obj_t * ui_Label24;
extern lv_obj_t * ui_btnShutdown;
extern lv_obj_t * ui_Label5;
extern lv_obj_t * ui_WLAN;
extern lv_obj_t * ui_Keyboard1;
extern void ui_event_InputPassKey(lv_event_t * e);
extern lv_obj_t * ui_InputPassKey;
extern lv_obj_t * ui_Label33;
extern lv_obj_t * ui_btnConnect;
extern lv_obj_t * ui_Label35;
extern lv_obj_t * ui_btnsearch;
extern lv_obj_t * ui_Label37;
extern void ui_event_btnSelectWifi(lv_event_t * e);
extern lv_obj_t * ui_btnSelectWifi;
extern lv_obj_t * ui_Label9;
extern lv_obj_t * ui_ssidList;
extern lv_obj_t * ui_savedSSIDs;
extern lv_obj_t * ui_PanelBatterySelect;
extern lv_obj_t * ui_ddCharchingSpeed1;
extern lv_obj_t * ui_ddCharchingSpeed2;
extern lv_obj_t * ui_ddCharchingSpeed3;
extern lv_obj_t * ui_ddCharchingSpeed4;
extern lv_obj_t * ui_ddCharchingSpeed5;
extern lv_obj_t * ui_ddCharchingSpeed6;
extern lv_obj_t * ui_ddCharchingSpeed7;
extern lv_obj_t * ui_ddCharchingSpeed8;
extern void ui_event_btnConfirmCharchingSpeed(lv_event_t * e);
extern lv_obj_t * ui_btnConfirmCharchingSpeed;
extern lv_obj_t * ui_Label3;
extern lv_obj_t * ui_Container3;
extern lv_obj_t * ui_OverlayOTAHelp;
extern lv_obj_t * ui_Label78;
extern lv_obj_t * ui_togglesim;
// CUSTOM VARIABLES
extern lv_obj_t * uic_TabView1;

#ifdef __cplusplus
} /*extern "C"*/
#endif

#endif

